### PR TITLE
FIx #264  Support Routes for Controllers in Sub-Packages

### LINKED ISSUE #264: Controllers in Sub Packages
the routing breaks if the controllers are in sub-packages

working:

```
- method: GET
  url: /
  mapping: ApplicationController.index
```

Not working:

```

- method: GET
  url: /api/v1/operator
  mapping: operator.OperatorListAPI.get
```

I have made a change in my branch to make it work, should i send a pull request? i see that as part of v5 routes.yaml is not needed?

### PR DESCRIPTION
**Pull request by gowthaman-basuvaraj**
Instead of splitting the mapping by just dot(.), this will split by the last dot('.') and take first part as controller and second part as Method

Example:

`ApplicationController.index`

Controller-> ApplicationController
Method -> index

`operator.OperatorListAPI.get`

Controller -> operator.OperatorListAPI
Method -> get

### CODE REVIEW

**Comment by svenkubiak** [comment]
Thanks for the fix! Happy to merge this and create a bugfix release. 

Unfortunatly tests are failing and we need a test-case for this.

Cheers,
Sven

**Comment by gowthaman-basuvaraj** [comment]
Will fix the tests, thanks

**Comment by svenkubiak** [comment]
I think you can reduce the Test-Case to just one method (e.g. GET). If the route is found in one subpackage, the other method will probably be found also. Also please remove the newly created item class. A test with a textbody should be sufficent.

Thanks! Great fix!

**Comment by svenkubiak** [comment]
Thanks again!

**Pull request merged**
