### PR TITLE
139v2

### PR DESCRIPTION
**Pull request by WilliamDunne**

### CODE REVIEW

**Comment by WilliamDunne** [comment]
If necessary I can solve the conflicts, however I think it's usually easier from the receiving side and I don't have write access.

**Comment by svenkubiak** [comment]
I'll close this for now, as it is easier for me to do some refactorings on the 2FAUtils class, rather than solving the merge conflicts. Once I am finished you can add your customizations okay. Ok?

**Comment by svenkubiak** [comment]
Just a quick additional question: as for the function to check the number for a given windows, wouldn't it be enough if we just make the generateCurrentNumber(String secret, long currentTimeMillis) public and let the user pass the required currentTimeMillis?

**Comment by svenkubiak** [comment]
Ok. I finished the refactorings, so feel free to add your customizations.

**Pull request closed without merging**
