### PR TITLE
Readme change

### PR DESCRIPTION
**Pull request by MrDunne**
I felt this was a slight improvement, I think it's a little easier to read
and I corrected a small spelling error.

### CODE REVIEW

**Comment by MarkVink** [comment]
The added method will throw a NullPointerException when the header Accept-Language does not exists in HeaderMap, (since you will call element() on null). Therefore it would be better to use the method getHeader() below.

**Comment by svenkubiak** [comment]
@MrDunne Was going to write the same thing ;-)

**Comment by MrDunne** [comment]
Ah okay, that makes sense. I had been looking for the constants as
I saw you use them elsewhere, but I was looking within the enum
secion of mangoo rather than Undertow. Performing that now.

**Comment by MrDunne** [comment]
Okay, that's done now.

**Pull request merged**
